version: "3.8"

services:
  
  graph-ql-api:
    image: graph-ql-api:1.0.0
    build:
      context: .    
      dockerfile: .docker/graph.dockerfile
    ports:
      - "1000:8080"
    volumes:
      - /Users/sameer/Code/Dota2API/logs:/app/logs
    networks:
      - my-docker-net
    depends_on:
      - mysql-db
    environment:
      - DATABASE_HOST=mysql-db
  
  grpc-api:
    image: grpc-api:1.0.0
    build:
      context: .
      dockerfile: .docker/grpc.dockerfile
    ports:
      - "2000:5050"
    volumes:
      - /Users/sameer/Code/Dota2API/logs:/app/logs
    networks:
      - my-docker-net
    depends_on:
      - mysql-db
    environment:
      - DATABASE_HOST=mysql-db
  
  mysql-db:
    image: dota2api-db
    build:
      context: .
      dockerfile: .docker/database.dockerfile
    restart: always
    networks:
      - my-docker-net
    volumes:
      - dota2vol:/var/lib/mysql
    environment:
     MYSQL_ROOT_PASSWORD: sameer123
     MYSQL_DATABASE: DotaDatabase
     MYSQL_ROOT_HOST: '%'
networks:
  my-docker-net:
    driver: bridge
volumes:
  dota2vol:


  
