// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.2
// source: models/grpc/dota2.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Attribute int32

const (
	Attribute_STRENGTH     Attribute = 0
	Attribute_AGILITY      Attribute = 1
	Attribute_INTELLIGENCE Attribute = 2
)

// Enum value maps for Attribute.
var (
	Attribute_name = map[int32]string{
		0: "STRENGTH",
		1: "AGILITY",
		2: "INTELLIGENCE",
	}
	Attribute_value = map[string]int32{
		"STRENGTH":     0,
		"AGILITY":      1,
		"INTELLIGENCE": 2,
	}
)

func (x Attribute) Enum() *Attribute {
	p := new(Attribute)
	*p = x
	return p
}

func (x Attribute) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Attribute) Descriptor() protoreflect.EnumDescriptor {
	return file_models_grpc_dota2_proto_enumTypes[0].Descriptor()
}

func (Attribute) Type() protoreflect.EnumType {
	return &file_models_grpc_dota2_proto_enumTypes[0]
}

func (x Attribute) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Attribute.Descriptor instead.
func (Attribute) EnumDescriptor() ([]byte, []int) {
	return file_models_grpc_dota2_proto_rawDescGZIP(), []int{0}
}

type AttackType int32

const (
	AttackType_MELEE  AttackType = 0
	AttackType_RANGED AttackType = 1
)

// Enum value maps for AttackType.
var (
	AttackType_name = map[int32]string{
		0: "MELEE",
		1: "RANGED",
	}
	AttackType_value = map[string]int32{
		"MELEE":  0,
		"RANGED": 1,
	}
)

func (x AttackType) Enum() *AttackType {
	p := new(AttackType)
	*p = x
	return p
}

func (x AttackType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttackType) Descriptor() protoreflect.EnumDescriptor {
	return file_models_grpc_dota2_proto_enumTypes[1].Descriptor()
}

func (AttackType) Type() protoreflect.EnumType {
	return &file_models_grpc_dota2_proto_enumTypes[1]
}

func (x AttackType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttackType.Descriptor instead.
func (AttackType) EnumDescriptor() ([]byte, []int) {
	return file_models_grpc_dota2_proto_rawDescGZIP(), []int{1}
}

type Role int32

const (
	Role_CARRY     Role = 0
	Role_NUKER     Role = 1
	Role_INITIATOR Role = 2
	Role_DISABLER  Role = 3
	Role_DURABLE   Role = 4
	Role_ESCAPE    Role = 5
	Role_SUPPORT   Role = 6
	Role_PUSHER    Role = 7
	Role_JUNGLER   Role = 8
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "CARRY",
		1: "NUKER",
		2: "INITIATOR",
		3: "DISABLER",
		4: "DURABLE",
		5: "ESCAPE",
		6: "SUPPORT",
		7: "PUSHER",
		8: "JUNGLER",
	}
	Role_value = map[string]int32{
		"CARRY":     0,
		"NUKER":     1,
		"INITIATOR": 2,
		"DISABLER":  3,
		"DURABLE":   4,
		"ESCAPE":    5,
		"SUPPORT":   6,
		"PUSHER":    7,
		"JUNGLER":   8,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_models_grpc_dota2_proto_enumTypes[2].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_models_grpc_dota2_proto_enumTypes[2]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_models_grpc_dota2_proto_rawDescGZIP(), []int{2}
}

type DamageType int32

const (
	DamageType_PHYSICAL DamageType = 0
	DamageType_MAGICAL  DamageType = 1
	DamageType_PURE     DamageType = 2
)

// Enum value maps for DamageType.
var (
	DamageType_name = map[int32]string{
		0: "PHYSICAL",
		1: "MAGICAL",
		2: "PURE",
	}
	DamageType_value = map[string]int32{
		"PHYSICAL": 0,
		"MAGICAL":  1,
		"PURE":     2,
	}
)

func (x DamageType) Enum() *DamageType {
	p := new(DamageType)
	*p = x
	return p
}

func (x DamageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DamageType) Descriptor() protoreflect.EnumDescriptor {
	return file_models_grpc_dota2_proto_enumTypes[3].Descriptor()
}

func (DamageType) Type() protoreflect.EnumType {
	return &file_models_grpc_dota2_proto_enumTypes[3]
}

func (x DamageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DamageType.Descriptor instead.
func (DamageType) EnumDescriptor() ([]byte, []int) {
	return file_models_grpc_dota2_proto_rawDescGZIP(), []int{3}
}

type AbilityBehavior int32

const (
	AbilityBehavior_PASSIVE AbilityBehavior = 0
	AbilityBehavior_ACTIVE  AbilityBehavior = 1
	AbilityBehavior_CHANNEL AbilityBehavior = 2
	AbilityBehavior_TOGGLED AbilityBehavior = 3
)

// Enum value maps for AbilityBehavior.
var (
	AbilityBehavior_name = map[int32]string{
		0: "PASSIVE",
		1: "ACTIVE",
		2: "CHANNEL",
		3: "TOGGLED",
	}
	AbilityBehavior_value = map[string]int32{
		"PASSIVE": 0,
		"ACTIVE":  1,
		"CHANNEL": 2,
		"TOGGLED": 3,
	}
)

func (x AbilityBehavior) Enum() *AbilityBehavior {
	p := new(AbilityBehavior)
	*p = x
	return p
}

func (x AbilityBehavior) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AbilityBehavior) Descriptor() protoreflect.EnumDescriptor {
	return file_models_grpc_dota2_proto_enumTypes[4].Descriptor()
}

func (AbilityBehavior) Type() protoreflect.EnumType {
	return &file_models_grpc_dota2_proto_enumTypes[4]
}

func (x AbilityBehavior) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AbilityBehavior.Descriptor instead.
func (AbilityBehavior) EnumDescriptor() ([]byte, []int) {
	return file_models_grpc_dota2_proto_rawDescGZIP(), []int{4}
}

type Hero struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string         `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	HeroName      string         `protobuf:"bytes,2,opt,name=HeroName,proto3" json:"HeroName,omitempty"`
	HeroAttribute Attribute      `protobuf:"varint,3,opt,name=HeroAttribute,proto3,enum=grpc.Attribute" json:"HeroAttribute,omitempty"`
	Role          []Role         `protobuf:"varint,4,rep,packed,name=Role,proto3,enum=grpc.Role" json:"Role,omitempty"`
	Abilities     []*HeroAbility `protobuf:"bytes,5,rep,name=Abilities,proto3" json:"Abilities,omitempty"`
}

func (x *Hero) Reset() {
	*x = Hero{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_grpc_dota2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hero) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hero) ProtoMessage() {}

func (x *Hero) ProtoReflect() protoreflect.Message {
	mi := &file_models_grpc_dota2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hero.ProtoReflect.Descriptor instead.
func (*Hero) Descriptor() ([]byte, []int) {
	return file_models_grpc_dota2_proto_rawDescGZIP(), []int{0}
}

func (x *Hero) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hero) GetHeroName() string {
	if x != nil {
		return x.HeroName
	}
	return ""
}

func (x *Hero) GetHeroAttribute() Attribute {
	if x != nil {
		return x.HeroAttribute
	}
	return Attribute_STRENGTH
}

func (x *Hero) GetRole() []Role {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *Hero) GetAbilities() []*HeroAbility {
	if x != nil {
		return x.Abilities
	}
	return nil
}

type HeroAbility struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name            string          `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Description     string          `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	DamageType      DamageType      `protobuf:"varint,3,opt,name=DamageType,proto3,enum=grpc.DamageType" json:"DamageType,omitempty"`
	AbilityBehavior AbilityBehavior `protobuf:"varint,4,opt,name=AbilityBehavior,proto3,enum=grpc.AbilityBehavior" json:"AbilityBehavior,omitempty"`
}

func (x *HeroAbility) Reset() {
	*x = HeroAbility{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_grpc_dota2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeroAbility) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroAbility) ProtoMessage() {}

func (x *HeroAbility) ProtoReflect() protoreflect.Message {
	mi := &file_models_grpc_dota2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroAbility.ProtoReflect.Descriptor instead.
func (*HeroAbility) Descriptor() ([]byte, []int) {
	return file_models_grpc_dota2_proto_rawDescGZIP(), []int{1}
}

func (x *HeroAbility) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HeroAbility) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *HeroAbility) GetDamageType() DamageType {
	if x != nil {
		return x.DamageType
	}
	return DamageType_PHYSICAL
}

func (x *HeroAbility) GetAbilityBehavior() AbilityBehavior {
	if x != nil {
		return x.AbilityBehavior
	}
	return AbilityBehavior_PASSIVE
}

type InGameHero struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hero    *Hero   `protobuf:"bytes,1,opt,name=Hero,proto3" json:"Hero,omitempty"`
	Items   []*Item `protobuf:"bytes,2,rep,name=Items,proto3" json:"Items,omitempty"`
	Gold    int32   `protobuf:"varint,3,opt,name=Gold,proto3" json:"Gold,omitempty"`
	XP      int32   `protobuf:"varint,4,opt,name=XP,proto3" json:"XP,omitempty"`
	Level   int32   `protobuf:"varint,5,opt,name=Level,proto3" json:"Level,omitempty"`
	Kills   int32   `protobuf:"varint,6,opt,name=Kills,proto3" json:"Kills,omitempty"`
	Deaths  int32   `protobuf:"varint,7,opt,name=Deaths,proto3" json:"Deaths,omitempty"`
	Assists int32   `protobuf:"varint,8,opt,name=Assists,proto3" json:"Assists,omitempty"`
}

func (x *InGameHero) Reset() {
	*x = InGameHero{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_grpc_dota2_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InGameHero) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InGameHero) ProtoMessage() {}

func (x *InGameHero) ProtoReflect() protoreflect.Message {
	mi := &file_models_grpc_dota2_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InGameHero.ProtoReflect.Descriptor instead.
func (*InGameHero) Descriptor() ([]byte, []int) {
	return file_models_grpc_dota2_proto_rawDescGZIP(), []int{2}
}

func (x *InGameHero) GetHero() *Hero {
	if x != nil {
		return x.Hero
	}
	return nil
}

func (x *InGameHero) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *InGameHero) GetGold() int32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *InGameHero) GetXP() int32 {
	if x != nil {
		return x.XP
	}
	return 0
}

func (x *InGameHero) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *InGameHero) GetKills() int32 {
	if x != nil {
		return x.Kills
	}
	return 0
}

func (x *InGameHero) GetDeaths() int32 {
	if x != nil {
		return x.Deaths
	}
	return 0
}

func (x *InGameHero) GetAssists() int32 {
	if x != nil {
		return x.Assists
	}
	return 0
}

type GetAllHeroesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllHeroesRequest) Reset() {
	*x = GetAllHeroesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_grpc_dota2_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllHeroesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllHeroesRequest) ProtoMessage() {}

func (x *GetAllHeroesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_grpc_dota2_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllHeroesRequest.ProtoReflect.Descriptor instead.
func (*GetAllHeroesRequest) Descriptor() ([]byte, []int) {
	return file_models_grpc_dota2_proto_rawDescGZIP(), []int{3}
}

type GetAllHeroesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hero []*Hero `protobuf:"bytes,1,rep,name=Hero,proto3" json:"Hero,omitempty"`
}

func (x *GetAllHeroesResponse) Reset() {
	*x = GetAllHeroesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_grpc_dota2_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllHeroesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllHeroesResponse) ProtoMessage() {}

func (x *GetAllHeroesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_models_grpc_dota2_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllHeroesResponse.ProtoReflect.Descriptor instead.
func (*GetAllHeroesResponse) Descriptor() ([]byte, []int) {
	return file_models_grpc_dota2_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllHeroesResponse) GetHero() []*Hero {
	if x != nil {
		return x.Hero
	}
	return nil
}

type GetHeroRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroId   int32  `protobuf:"varint,1,opt,name=HeroId,proto3" json:"HeroId,omitempty"`
	HeroName string `protobuf:"bytes,2,opt,name=HeroName,proto3" json:"HeroName,omitempty"`
}

func (x *GetHeroRequest) Reset() {
	*x = GetHeroRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_grpc_dota2_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHeroRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeroRequest) ProtoMessage() {}

func (x *GetHeroRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_grpc_dota2_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeroRequest.ProtoReflect.Descriptor instead.
func (*GetHeroRequest) Descriptor() ([]byte, []int) {
	return file_models_grpc_dota2_proto_rawDescGZIP(), []int{5}
}

func (x *GetHeroRequest) GetHeroId() int32 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

func (x *GetHeroRequest) GetHeroName() string {
	if x != nil {
		return x.HeroName
	}
	return ""
}

type MatchDetailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchID               int32         `protobuf:"varint,1,opt,name=MatchID,proto3" json:"MatchID,omitempty"`
	DireKills             int32         `protobuf:"varint,2,opt,name=DireKills,proto3" json:"DireKills,omitempty"`
	RadiantKills          int32         `protobuf:"varint,3,opt,name=RadiantKills,proto3" json:"RadiantKills,omitempty"`
	Duration              float32       `protobuf:"fixed32,4,opt,name=Duration,proto3" json:"Duration,omitempty"`
	GameMode              int32         `protobuf:"varint,5,opt,name=GameMode,proto3" json:"GameMode,omitempty"`
	GoldAdvantage         int32         `protobuf:"varint,6,opt,name=GoldAdvantage,proto3" json:"GoldAdvantage,omitempty"`
	XPAdvantage           int32         `protobuf:"varint,7,opt,name=XPAdvantage,proto3" json:"XPAdvantage,omitempty"`
	RadiantTowersKilled   int32         `protobuf:"varint,8,opt,name=RadiantTowersKilled,proto3" json:"RadiantTowersKilled,omitempty"`
	DireTowersKilled      int32         `protobuf:"varint,9,opt,name=DireTowersKilled,proto3" json:"DireTowersKilled,omitempty"`
	RadiantBarracksKilled int32         `protobuf:"varint,10,opt,name=RadiantBarracksKilled,proto3" json:"RadiantBarracksKilled,omitempty"`
	DireBaracksKilled     int32         `protobuf:"varint,11,opt,name=DireBaracksKilled,proto3" json:"DireBaracksKilled,omitempty"`
	RadiantHeroes         []*InGameHero `protobuf:"bytes,12,rep,name=RadiantHeroes,proto3" json:"RadiantHeroes,omitempty"`
	DireHeros             []*InGameHero `protobuf:"bytes,13,rep,name=DireHeros,proto3" json:"DireHeros,omitempty"`
}

func (x *MatchDetailsResponse) Reset() {
	*x = MatchDetailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_grpc_dota2_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchDetailsResponse) ProtoMessage() {}

func (x *MatchDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_models_grpc_dota2_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchDetailsResponse.ProtoReflect.Descriptor instead.
func (*MatchDetailsResponse) Descriptor() ([]byte, []int) {
	return file_models_grpc_dota2_proto_rawDescGZIP(), []int{6}
}

func (x *MatchDetailsResponse) GetMatchID() int32 {
	if x != nil {
		return x.MatchID
	}
	return 0
}

func (x *MatchDetailsResponse) GetDireKills() int32 {
	if x != nil {
		return x.DireKills
	}
	return 0
}

func (x *MatchDetailsResponse) GetRadiantKills() int32 {
	if x != nil {
		return x.RadiantKills
	}
	return 0
}

func (x *MatchDetailsResponse) GetDuration() float32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *MatchDetailsResponse) GetGameMode() int32 {
	if x != nil {
		return x.GameMode
	}
	return 0
}

func (x *MatchDetailsResponse) GetGoldAdvantage() int32 {
	if x != nil {
		return x.GoldAdvantage
	}
	return 0
}

func (x *MatchDetailsResponse) GetXPAdvantage() int32 {
	if x != nil {
		return x.XPAdvantage
	}
	return 0
}

func (x *MatchDetailsResponse) GetRadiantTowersKilled() int32 {
	if x != nil {
		return x.RadiantTowersKilled
	}
	return 0
}

func (x *MatchDetailsResponse) GetDireTowersKilled() int32 {
	if x != nil {
		return x.DireTowersKilled
	}
	return 0
}

func (x *MatchDetailsResponse) GetRadiantBarracksKilled() int32 {
	if x != nil {
		return x.RadiantBarracksKilled
	}
	return 0
}

func (x *MatchDetailsResponse) GetDireBaracksKilled() int32 {
	if x != nil {
		return x.DireBaracksKilled
	}
	return 0
}

func (x *MatchDetailsResponse) GetRadiantHeroes() []*InGameHero {
	if x != nil {
		return x.RadiantHeroes
	}
	return nil
}

func (x *MatchDetailsResponse) GetDireHeros() []*InGameHero {
	if x != nil {
		return x.DireHeros
	}
	return nil
}

type MatchDetailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchID int32 `protobuf:"varint,1,opt,name=MatchID,proto3" json:"MatchID,omitempty"`
}

func (x *MatchDetailsRequest) Reset() {
	*x = MatchDetailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_grpc_dota2_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchDetailsRequest) ProtoMessage() {}

func (x *MatchDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_grpc_dota2_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchDetailsRequest.ProtoReflect.Descriptor instead.
func (*MatchDetailsRequest) Descriptor() ([]byte, []int) {
	return file_models_grpc_dota2_proto_rawDescGZIP(), []int{7}
}

func (x *MatchDetailsRequest) GetMatchID() int32 {
	if x != nil {
		return x.MatchID
	}
	return 0
}

type MatchIDsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MatchIDsRequest) Reset() {
	*x = MatchIDsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_grpc_dota2_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchIDsRequest) ProtoMessage() {}

func (x *MatchIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_grpc_dota2_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchIDsRequest.ProtoReflect.Descriptor instead.
func (*MatchIDsRequest) Descriptor() ([]byte, []int) {
	return file_models_grpc_dota2_proto_rawDescGZIP(), []int{8}
}

type MatchIDsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchID int32 `protobuf:"varint,1,opt,name=MatchID,proto3" json:"MatchID,omitempty"`
}

func (x *MatchIDsResponse) Reset() {
	*x = MatchIDsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_grpc_dota2_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchIDsResponse) ProtoMessage() {}

func (x *MatchIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_models_grpc_dota2_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchIDsResponse.ProtoReflect.Descriptor instead.
func (*MatchIDsResponse) Descriptor() ([]byte, []int) {
	return file_models_grpc_dota2_proto_rawDescGZIP(), []int{9}
}

func (x *MatchIDsResponse) GetMatchID() int32 {
	if x != nil {
		return x.MatchID
	}
	return 0
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Id   int32    `protobuf:"varint,2,opt,name=Id,proto3" json:"Id,omitempty"`
	Cost int32    `protobuf:"varint,3,opt,name=Cost,proto3" json:"Cost,omitempty"`
	Hint []string `protobuf:"bytes,4,rep,name=Hint,proto3" json:"Hint,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_grpc_dota2_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_models_grpc_dota2_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_models_grpc_dota2_proto_rawDescGZIP(), []int{10}
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetCost() int32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *Item) GetHint() []string {
	if x != nil {
		return x.Hint
	}
	return nil
}

type GetAllItemsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllItemsRequest) Reset() {
	*x = GetAllItemsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_grpc_dota2_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllItemsRequest) ProtoMessage() {}

func (x *GetAllItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_grpc_dota2_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllItemsRequest.ProtoReflect.Descriptor instead.
func (*GetAllItemsRequest) Descriptor() ([]byte, []int) {
	return file_models_grpc_dota2_proto_rawDescGZIP(), []int{11}
}

type GetAllItemsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Item `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
}

func (x *GetAllItemsResponse) Reset() {
	*x = GetAllItemsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_grpc_dota2_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllItemsResponse) ProtoMessage() {}

func (x *GetAllItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_models_grpc_dota2_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllItemsResponse.ProtoReflect.Descriptor instead.
func (*GetAllItemsResponse) Descriptor() ([]byte, []int) {
	return file_models_grpc_dota2_proto_rawDescGZIP(), []int{12}
}

func (x *GetAllItemsResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId int32  `protobuf:"varint,1,opt,name=ItemId,proto3" json:"ItemId,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_grpc_dota2_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_grpc_dota2_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemRequest.ProtoReflect.Descriptor instead.
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return file_models_grpc_dota2_proto_rawDescGZIP(), []int{13}
}

func (x *GetItemRequest) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *GetItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_models_grpc_dota2_proto protoreflect.FileDescriptor

var file_models_grpc_dota2_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x64, 0x6f,
	0x74, 0x61, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22,
	0xbe, 0x01, 0x0a, 0x04, 0x48, 0x65, 0x72, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x48, 0x65, 0x72, 0x6f, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x48, 0x65, 0x72, 0x6f, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x35, 0x0a, 0x0d, 0x48, 0x65, 0x72, 0x6f,
	0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x52, 0x0d, 0x48, 0x65, 0x72, 0x6f, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12,
	0x1e, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x0a, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12,
	0x2f, 0x0a, 0x09, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x48, 0x65, 0x72, 0x6f, 0x41, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x09, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73,
	0x22, 0xb6, 0x01, 0x0a, 0x0b, 0x48, 0x65, 0x72, 0x6f, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x0a, 0x44, 0x61, 0x6d, 0x61, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x44, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x44, 0x61,
	0x6d, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3f, 0x0a, 0x0f, 0x41, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x52, 0x0f, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x22, 0xd0, 0x01, 0x0a, 0x0a, 0x49, 0x6e,
	0x47, 0x61, 0x6d, 0x65, 0x48, 0x65, 0x72, 0x6f, 0x12, 0x1e, 0x0a, 0x04, 0x48, 0x65, 0x72, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x48, 0x65,
	0x72, 0x6f, 0x52, 0x04, 0x48, 0x65, 0x72, 0x6f, 0x12, 0x20, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x47, 0x6f,
	0x6c, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x47, 0x6f, 0x6c, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x58, 0x50, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x58, 0x50, 0x12, 0x14,
	0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x4b, 0x69, 0x6c, 0x6c, 0x73, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x4b, 0x69, 0x6c, 0x6c, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x65,
	0x61, 0x74, 0x68, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x44, 0x65, 0x61, 0x74,
	0x68, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x73, 0x73, 0x69, 0x73, 0x74, 0x73, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x41, 0x73, 0x73, 0x69, 0x73, 0x74, 0x73, 0x22, 0x15, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x48, 0x65, 0x72, 0x6f, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x36, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x48, 0x65, 0x72,
	0x6f, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x48,
	0x65, 0x72, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x48, 0x65, 0x72, 0x6f, 0x52, 0x04, 0x48, 0x65, 0x72, 0x6f, 0x22, 0x44, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x48, 0x65, 0x72, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x48, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x48,
	0x65, 0x72, 0x6f, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x48, 0x65, 0x72, 0x6f, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x48, 0x65, 0x72, 0x6f, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x9c, 0x04, 0x0a, 0x14, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x44, 0x69, 0x72, 0x65, 0x4b, 0x69, 0x6c, 0x6c,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x44, 0x69, 0x72, 0x65, 0x4b, 0x69, 0x6c,
	0x6c, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x52, 0x61, 0x64, 0x69, 0x61, 0x6e, 0x74, 0x4b, 0x69, 0x6c,
	0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x52, 0x61, 0x64, 0x69, 0x61, 0x6e,
	0x74, 0x4b, 0x69, 0x6c, 0x6c, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x24,
	0x0a, 0x0d, 0x47, 0x6f, 0x6c, 0x64, 0x41, 0x64, 0x76, 0x61, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x47, 0x6f, 0x6c, 0x64, 0x41, 0x64, 0x76, 0x61, 0x6e,
	0x74, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x58, 0x50, 0x41, 0x64, 0x76, 0x61, 0x6e, 0x74,
	0x61, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x58, 0x50, 0x41, 0x64, 0x76,
	0x61, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x12, 0x30, 0x0a, 0x13, 0x52, 0x61, 0x64, 0x69, 0x61, 0x6e,
	0x74, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x4b, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x13, 0x52, 0x61, 0x64, 0x69, 0x61, 0x6e, 0x74, 0x54, 0x6f, 0x77, 0x65,
	0x72, 0x73, 0x4b, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x10, 0x44, 0x69, 0x72, 0x65,
	0x54, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x4b, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x10, 0x44, 0x69, 0x72, 0x65, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x4b, 0x69,
	0x6c, 0x6c, 0x65, 0x64, 0x12, 0x34, 0x0a, 0x15, 0x52, 0x61, 0x64, 0x69, 0x61, 0x6e, 0x74, 0x42,
	0x61, 0x72, 0x72, 0x61, 0x63, 0x6b, 0x73, 0x4b, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x15, 0x52, 0x61, 0x64, 0x69, 0x61, 0x6e, 0x74, 0x42, 0x61, 0x72, 0x72,
	0x61, 0x63, 0x6b, 0x73, 0x4b, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x12, 0x2c, 0x0a, 0x11, 0x44, 0x69,
	0x72, 0x65, 0x42, 0x61, 0x72, 0x61, 0x63, 0x6b, 0x73, 0x4b, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x44, 0x69, 0x72, 0x65, 0x42, 0x61, 0x72, 0x61, 0x63,
	0x6b, 0x73, 0x4b, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x12, 0x36, 0x0a, 0x0d, 0x52, 0x61, 0x64, 0x69,
	0x61, 0x6e, 0x74, 0x48, 0x65, 0x72, 0x6f, 0x65, 0x73, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x48, 0x65, 0x72,
	0x6f, 0x52, 0x0d, 0x52, 0x61, 0x64, 0x69, 0x61, 0x6e, 0x74, 0x48, 0x65, 0x72, 0x6f, 0x65, 0x73,
	0x12, 0x2e, 0x0a, 0x09, 0x44, 0x69, 0x72, 0x65, 0x48, 0x65, 0x72, 0x6f, 0x73, 0x18, 0x0d, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x6e, 0x47, 0x61, 0x6d,
	0x65, 0x48, 0x65, 0x72, 0x6f, 0x52, 0x09, 0x44, 0x69, 0x72, 0x65, 0x48, 0x65, 0x72, 0x6f, 0x73,
	0x22, 0x2f, 0x0a, 0x13, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x49,
	0x44, 0x22, 0x11, 0x0a, 0x0f, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x2c, 0x0a, 0x10, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x44, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x49, 0x44, 0x22, 0x52, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x43, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x69, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x04, 0x48, 0x69, 0x6e, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x37, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x3c, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x74, 0x65, 0x6d, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x2a, 0x38, 0x0a, 0x09, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x12, 0x0c, 0x0a, 0x08, 0x53, 0x54, 0x52, 0x45, 0x4e, 0x47, 0x54, 0x48, 0x10, 0x00, 0x12, 0x0b,
	0x0a, 0x07, 0x41, 0x47, 0x49, 0x4c, 0x49, 0x54, 0x59, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x49,
	0x4e, 0x54, 0x45, 0x4c, 0x4c, 0x49, 0x47, 0x45, 0x4e, 0x43, 0x45, 0x10, 0x02, 0x2a, 0x23, 0x0a,
	0x0a, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x4d,
	0x45, 0x4c, 0x45, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x41, 0x4e, 0x47, 0x45, 0x44,
	0x10, 0x01, 0x2a, 0x78, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x41,
	0x52, 0x52, 0x59, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4e, 0x55, 0x4b, 0x45, 0x52, 0x10, 0x01,
	0x12, 0x0d, 0x0a, 0x09, 0x49, 0x4e, 0x49, 0x54, 0x49, 0x41, 0x54, 0x4f, 0x52, 0x10, 0x02, 0x12,
	0x0c, 0x0a, 0x08, 0x44, 0x49, 0x53, 0x41, 0x42, 0x4c, 0x45, 0x52, 0x10, 0x03, 0x12, 0x0b, 0x0a,
	0x07, 0x44, 0x55, 0x52, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x45, 0x53,
	0x43, 0x41, 0x50, 0x45, 0x10, 0x05, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x50, 0x50, 0x4f, 0x52,
	0x54, 0x10, 0x06, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x55, 0x53, 0x48, 0x45, 0x52, 0x10, 0x07, 0x12,
	0x0b, 0x0a, 0x07, 0x4a, 0x55, 0x4e, 0x47, 0x4c, 0x45, 0x52, 0x10, 0x08, 0x2a, 0x31, 0x0a, 0x0a,
	0x44, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x48,
	0x59, 0x53, 0x49, 0x43, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x41, 0x47, 0x49,
	0x43, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x55, 0x52, 0x45, 0x10, 0x02, 0x2a,
	0x44, 0x0a, 0x0f, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69,
	0x6f, 0x72, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x41, 0x53, 0x53, 0x49, 0x56, 0x45, 0x10, 0x00, 0x12,
	0x0a, 0x0a, 0x06, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x43,
	0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x54, 0x4f, 0x47, 0x47,
	0x4c, 0x45, 0x44, 0x10, 0x03, 0x32, 0x82, 0x03, 0x0a, 0x0c, 0x44, 0x6f, 0x74, 0x61, 0x32, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x48, 0x65, 0x72, 0x6f, 0x65, 0x73, 0x12, 0x19, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x48, 0x65, 0x72, 0x6f, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x48,
	0x65, 0x72, 0x6f, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a,
	0x07, 0x47, 0x65, 0x74, 0x48, 0x65, 0x72, 0x6f, 0x12, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x47, 0x65, 0x74, 0x48, 0x65, 0x72, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x48, 0x65, 0x72, 0x6f, 0x12, 0x42, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b,
	0x0a, 0x07, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x41, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x4c, 0x69, 0x76, 0x65, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x12, 0x15, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x49, 0x44, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x4a,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x12, 0x19, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x73, 0x6b, 0x73, 0x61, 0x6d, 0x65,
	0x65, 0x72, 0x35, 0x36, 0x2f, 0x44, 0x6f, 0x74, 0x61, 0x32, 0x41, 0x50, 0x49, 0x2f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_models_grpc_dota2_proto_rawDescOnce sync.Once
	file_models_grpc_dota2_proto_rawDescData = file_models_grpc_dota2_proto_rawDesc
)

func file_models_grpc_dota2_proto_rawDescGZIP() []byte {
	file_models_grpc_dota2_proto_rawDescOnce.Do(func() {
		file_models_grpc_dota2_proto_rawDescData = protoimpl.X.CompressGZIP(file_models_grpc_dota2_proto_rawDescData)
	})
	return file_models_grpc_dota2_proto_rawDescData
}

var file_models_grpc_dota2_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_models_grpc_dota2_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_models_grpc_dota2_proto_goTypes = []interface{}{
	(Attribute)(0),               // 0: grpc.Attribute
	(AttackType)(0),              // 1: grpc.AttackType
	(Role)(0),                    // 2: grpc.Role
	(DamageType)(0),              // 3: grpc.DamageType
	(AbilityBehavior)(0),         // 4: grpc.AbilityBehavior
	(*Hero)(nil),                 // 5: grpc.Hero
	(*HeroAbility)(nil),          // 6: grpc.HeroAbility
	(*InGameHero)(nil),           // 7: grpc.InGameHero
	(*GetAllHeroesRequest)(nil),  // 8: grpc.GetAllHeroesRequest
	(*GetAllHeroesResponse)(nil), // 9: grpc.GetAllHeroesResponse
	(*GetHeroRequest)(nil),       // 10: grpc.GetHeroRequest
	(*MatchDetailsResponse)(nil), // 11: grpc.MatchDetailsResponse
	(*MatchDetailsRequest)(nil),  // 12: grpc.MatchDetailsRequest
	(*MatchIDsRequest)(nil),      // 13: grpc.MatchIDsRequest
	(*MatchIDsResponse)(nil),     // 14: grpc.MatchIDsResponse
	(*Item)(nil),                 // 15: grpc.Item
	(*GetAllItemsRequest)(nil),   // 16: grpc.GetAllItemsRequest
	(*GetAllItemsResponse)(nil),  // 17: grpc.GetAllItemsResponse
	(*GetItemRequest)(nil),       // 18: grpc.GetItemRequest
}
var file_models_grpc_dota2_proto_depIdxs = []int32{
	0,  // 0: grpc.Hero.HeroAttribute:type_name -> grpc.Attribute
	2,  // 1: grpc.Hero.Role:type_name -> grpc.Role
	6,  // 2: grpc.Hero.Abilities:type_name -> grpc.HeroAbility
	3,  // 3: grpc.HeroAbility.DamageType:type_name -> grpc.DamageType
	4,  // 4: grpc.HeroAbility.AbilityBehavior:type_name -> grpc.AbilityBehavior
	5,  // 5: grpc.InGameHero.Hero:type_name -> grpc.Hero
	15, // 6: grpc.InGameHero.Items:type_name -> grpc.Item
	5,  // 7: grpc.GetAllHeroesResponse.Hero:type_name -> grpc.Hero
	7,  // 8: grpc.MatchDetailsResponse.RadiantHeroes:type_name -> grpc.InGameHero
	7,  // 9: grpc.MatchDetailsResponse.DireHeros:type_name -> grpc.InGameHero
	15, // 10: grpc.GetAllItemsResponse.Items:type_name -> grpc.Item
	8,  // 11: grpc.Dota2Service.GetAllHeroes:input_type -> grpc.GetAllHeroesRequest
	10, // 12: grpc.Dota2Service.GetHero:input_type -> grpc.GetHeroRequest
	16, // 13: grpc.Dota2Service.GetAllItems:input_type -> grpc.GetAllItemsRequest
	18, // 14: grpc.Dota2Service.GetItem:input_type -> grpc.GetItemRequest
	13, // 15: grpc.Dota2Service.GetLiveMatches:input_type -> grpc.MatchIDsRequest
	12, // 16: grpc.Dota2Service.GetMatchDetails:input_type -> grpc.MatchDetailsRequest
	9,  // 17: grpc.Dota2Service.GetAllHeroes:output_type -> grpc.GetAllHeroesResponse
	5,  // 18: grpc.Dota2Service.GetHero:output_type -> grpc.Hero
	17, // 19: grpc.Dota2Service.GetAllItems:output_type -> grpc.GetAllItemsResponse
	15, // 20: grpc.Dota2Service.GetItem:output_type -> grpc.Item
	14, // 21: grpc.Dota2Service.GetLiveMatches:output_type -> grpc.MatchIDsResponse
	11, // 22: grpc.Dota2Service.GetMatchDetails:output_type -> grpc.MatchDetailsResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_models_grpc_dota2_proto_init() }
func file_models_grpc_dota2_proto_init() {
	if File_models_grpc_dota2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_models_grpc_dota2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hero); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_grpc_dota2_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeroAbility); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_grpc_dota2_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InGameHero); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_grpc_dota2_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllHeroesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_grpc_dota2_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllHeroesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_grpc_dota2_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHeroRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_grpc_dota2_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchDetailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_grpc_dota2_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchDetailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_grpc_dota2_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchIDsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_grpc_dota2_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchIDsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_grpc_dota2_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_grpc_dota2_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllItemsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_grpc_dota2_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllItemsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_grpc_dota2_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_models_grpc_dota2_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_models_grpc_dota2_proto_goTypes,
		DependencyIndexes: file_models_grpc_dota2_proto_depIdxs,
		EnumInfos:         file_models_grpc_dota2_proto_enumTypes,
		MessageInfos:      file_models_grpc_dota2_proto_msgTypes,
	}.Build()
	File_models_grpc_dota2_proto = out.File
	file_models_grpc_dota2_proto_rawDesc = nil
	file_models_grpc_dota2_proto_goTypes = nil
	file_models_grpc_dota2_proto_depIdxs = nil
}
